// Builds the studio page. apps/desktop/views/editor.html is the template: each
// `<!-- include name.html -->` line is replaced by that file from the same
// folder, indented to match, and the result is written to
// apps/desktop/editor.html, which the app and the UI tests load. The editors'
// markup lives in views/ so it can be read and edited as indented HTML.
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const desktop = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../apps/desktop');
const views = path.join(desktop, 'views');
const INCLUDE = /^([ \t]*)<!-- include ([\w-]+\.html) -->[ \t]*$/gm;

const template = await readFile(path.join(views, 'editor.html'), 'utf8');
const parts = [];
for (const match of template.matchAll(INCLUDE)) {
  const [, indent, name] = match;
  const text = (await readFile(path.join(views, name), 'utf8')).trimEnd();
  parts.push({ match, text: text.replace(/^(?=.)/gm, indent) });
}
let page = '',
  at = 0;
for (const { match, text } of parts) {
  page += template.slice(at, match.index) + text;
  at = match.index + match[0].length;
}
page += template.slice(at);
const notice =
  '<!-- Generated by scripts/build-page.mjs from views/editor.html. Edit the files in views/. -->\n';
await writeFile(
  path.join(desktop, 'editor.html'),
  page.replace(/^(<!doctype html>\n)/i, `$1${notice}`),
);
